[package]
name = "lean"
version = "0.1"
lean_version = "nightly-2018-11-13"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", branch = "limits-other", rev = "81696f007d6ed77497d14b2b8fddeb9228a5cddb"}
